const { withProjectBuildGradle, withAppBuildGradle, withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

// google-services (the Firebase gradle plugin that processes google-services.json
// into resources) is not published to Maven Central via the RN autolink, so it
// must be wired by hand. Because android/ is generated by prebuild (CNG), this
// config plugin re-applies the wiring on every prebuild.
const GOOGLE_SERVICES_VERSION = '4.4.2';

// 1. Add the google-services classpath to the project build.gradle.
function withGoogleServicesClasspath(config) {
  return withProjectBuildGradle(config, (cfg) => {
    const line = `classpath('com.google.gms:google-services:${GOOGLE_SERVICES_VERSION}')`;
    if (!cfg.modResults.contents.includes(line)) {
      cfg.modResults.contents = cfg.modResults.contents.replace(
        /dependencies\s*\{/,
        (m) => `${m}\n        ${line}`
      );
    }
    return cfg;
  });
}

// 2. Apply the google-services plugin in the app build.gradle.
function withApplyGoogleServices(config) {
  return withAppBuildGradle(config, (cfg) => {
    const line = "apply plugin: 'com.google.gms.google-services'";
    if (!cfg.modResults.contents.includes(line)) {
      cfg.modResults.contents += `\n${line}\n`;
    }
    return cfg;
  });
}

// 3. Copy google-services.json (repo root) into android/app/ during prebuild.
function withGoogleServicesJson(config) {
  return withDangerousMod(config, [
    'android',
    (cfg) => {
      const src = path.join(cfg.modRequest.projectRoot, 'google-services.json');
      const dest = path.join(cfg.modRequest.platformProjectRoot, 'app', 'google-services.json');
      if (!fs.existsSync(src)) {
        throw new Error('[withAndroidFcm] google-services.json not found at project root');
      }
      fs.copyFileSync(src, dest);
      return cfg;
    },
  ]);
}

module.exports = (config) =>
  withGoogleServicesJson(withApplyGoogleServices(withGoogleServicesClasspath(config)));
